---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_solo
  require_chef_omnibus: true

platforms:
  - name: centos-6.5
  - name: ubuntu-12.04
    run_list: apt::default

suites:
#  - name: default
#    run_list:
#      - recipe[hadoop::default]
#    attributes: {}
  - name: cdh4
    run_list:
      - recipe[hadoop::default]
      - recipe[minitest-handler::default]
    attributes: { hadoop: { distribution: 'cdh', distribution_version: 4 } }
  - name: cdh5
    run_list:
      - recipe[hadoop::default]
      - recipe[minitest-handler::default]
    attributes: { hadoop: { distribution: 'cdh', distribution_version: 5 } }
  - name: hdp20
    run_list:
      - recipe[hadoop::default]
      - recipe[minitest-handler::default]
    attributes: { hadoop: { distribution: 'hdp', distribution_version: '2.0' } }
  - name: hdp21
    run_list:
      - recipe[hadoop::default]
      - recipe[minitest-handler::default]
    attributes: { hadoop: { distribution: 'hdp', distribution_version: '2.1' } }
